services:
  web-app:
    build:
      context: ./web-app
    container_name: web-app
    environment:
      - NEXT_PUBLIC_EDGE_API_URL=http://localhost:3000
    ports:
      - "4000:4000"
    depends_on:
      - edge-api

  core-api:
    build:
      context: ./core-api
    container_name: core-api
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://postgres:5432/spotify_analytics
      - DB_USERNAME=spotify
      - DB_PASSWORD=spotify
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TOKEN_SECRET=local-dev-change-me
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  edge-api:
    build:
      context: ./edge-api
    container_name: edge-api
    environment:
      - PORT=3000
      - CORE_API_URL=http://core-api:8080
      - SESSION_SECRET=local-dev-session-secret
      - SPOTIFY_CLIENT_ID=4137aa09f0274e49b568ca39d9dfa4af
      - SPOTIFY_REDIRECT_URI=http://localhost:3000/auth/spotify/callback
      - OIDC_REDIRECT_URI=http://localhost:3000/auth/session/callback
    ports:
      - "3000:3000"
    depends_on:
      - core-api

  postgres:
    image: postgres:16
    container_name: spotify-postgres
    environment:
      POSTGRES_USER: spotify
      POSTGRES_PASSWORD: spotify
      POSTGRES_DB: spotify_analytics
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: spotify-redis
    ports:
      - "6379:6379"

  otel-collector:
    image: otel/opentelemetry-collector:0.111.0
    container_name: otel-collector
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./observability/otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"

volumes:
  pgdata:
